# -*- coding: utf-8 -*-
"""BE21F03F054_Linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvhTncpANfeZcnFQfPvYSsKFkimnainX
"""

import pandas as pd
df = pd.read_csv("/content/Book1.csv")
df.head()

import matplotlib.pyplot as plt
plt.scatter(df['X'],df['Y'])
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

from sklearn.linear_model import LinearRegression
x = df[['X']].values
y = df['Y'].values
reg = LinearRegression()
reg.fit(x,y)

m = reg.coef_[0]
c = reg.intercept_
m = round(m, 3)
c = round(c, 3)
print(m)
print(c)
print("The equation of straight line is y = mx + c")
print(f"Equation:y={m}x+{c}")

reg.predict([[15]])

# Plot the scatter plot of the data
plt.scatter(df['X'], df['Y'], label='Data')
plt.xlabel('X')
plt.ylabel('Y')

# Perform linear regression
x = df[['X']].values
y = df['Y'].values
reg = LinearRegression()
reg.fit(x, y)

# Get the slope (m) and intercept (c) of the regression line
m = reg.coef_[0]
c = reg.intercept_

# Plot the linear regression line
plt.plot(df['X'], m * df['X'] + c, color='red', label='Linear Regression')

# Add legend
plt.legend()

# Show plot
plt.show()