# -*- coding: utf-8 -*-
"""BE21F03F049_Agglomerative Hierarchical Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xsWE0v_TGQZL1rZJvVmtmgHNvdy2zS_
"""

import pandas as pd
import numpy as np
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage

# Load the data
data = pd.read_csv('/content/file.csv')

# Perform hierarchical clustering
X = data[['X', 'Y']].values
clustering = AgglomerativeClustering(n_clusters=3, affinity='euclidean', linkage='ward', distance_threshold=None)
clustering.fit(X)

# Get the cluster labels
labels = clustering.labels_

# Create a dendrogram
plt.figure(figsize=(10, 6))
linkage_matrix = linkage(X, 'ward')
dendrogram(linkage_matrix)
plt.title('Hierarchical Clustering Dendrogram')
plt.xlabel('Data point')
plt.ylabel('Distance')
plt.show()

# Print the cluster labels
print('Cluster labels:', labels)

